POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "Blog2",
    "author": "Author2",
    "url": "blog2.com",
    "likes": 2,
    "userId": "5fdf9d8db924c128a0aae296"
}